# Generated by Django 4.0.3 on 2023-04-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_zipcode'),
    ]

    operations = [
    ]
