# Generated by Django 4.0.3 on 2023-04-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230425_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membreship',
            new_name='membership',
        ),
    ]
