# Generated by Django 4.0.3 on 2023-04-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_membreship_customer_membership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
    ]
